name: dolar_hoy
description: 'Revisa el valor del dolar en Venezuela de forma sencilla y rápida.'
publish_to: 'none'
version: 0.0.6

environment:
    sdk: ^3.8.0

dependencies:
    bloc: ^9.0.0
    dio: ^5.8.0+1
    equatable: ^2.0.7
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_dotenv: ^5.2.1
    go_router: ^15.1.2
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
