name: dolar_hoy
description: 'Revisa el valor del dolar en Venezuela de forma sencilla y rápida.'
publish_to: 'none'
version: 0.0.1

environment:
    sdk: ^3.8.0

dependencies:
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.2.1
    go_router: ^15.1.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
