name: dolar_hoy
description: 'Revisa el valor del dolar en Venezuela de forma sencilla y rápida.'
publish_to: 'none'
version: 0.3.0

environment:
    sdk: ^3.8.0

dependencies:
    animate_do: ^4.2.0
    bloc: ^9.0.0
    dio: ^5.8.0+1
    equatable: ^2.0.7
    flutter:
        sdk: flutter
    flutter_bloc: ^9.1.1
    flutter_dotenv: ^5.2.1
    flutter_launcher_icons: ^0.14.3
    go_router: ^15.1.2
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - .env
        - assets/icon/

flutter_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/icon/launcher_icon.png'
    web:
        generate: true
        image_path: 'assets/icon/launcher_icon.png'
